[dev]
functions = "src/functions"
publish = "public"
[build]
functions = "src/functions"
publish = "public"
 [[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript" }
[[redirects]]
  from = "/:restaurant/restaurantManager/:classe"
  to = "restaurant/restaurantManager/:classe"
  status = 200
[[redirects]]
  from = "/"
  to = "introduction-pages/main/"
  status = 301
  force=true
[[redirects]]
  from = "/:restaurant/solicitar-pedido"
  to = ".netlify/functions/" 

[[redirects]]
  from = "/:restaurant/client-request/:classe"
  to = "restaurant/client-request/:classe"
  status = 200

[[redirects]]
  from = "/tste/*"
  to = "tste/:splat"
  status = 301